# After changing this file, check it on:
#   http://lint.travis-ci.org/
#

dist: trusty
sudo: required
language: python
matrix:
  fast_finish: true
  include:
  - python: 2.7
    env:
    - PYTHON=3.6
  - python: 2.7
    env:
      - PYTHON=3.7
  - python: 2.7
    env:
      - PYTHON=3.8
      - COVERAGE=true
# Setup anaconda
before_install:
  - sudo apt update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda config --add channels conda-forge
install:
  - DEPS="numpy scipy pip pytest matplotlib mock pandas statsmodels"
  - conda create -q -n test-environment python=$PYTHON $DEPS
  - source activate test-environment
  - if [ ${COVERAGE} = true ]; then export COVERAGE_OPTS=" --cov-config=.travis_coveragerc --cov=causalimpact "; else export COVERAGE_OPTS=""; fi
  - if [ ${COVERAGE} = true ]; then pip install codecov coverage coveralls pytest-cov mock; fi
  - python setup.py install
script:
  - pytest ${COVERAGE_OPTS} causalimpact
after_success:
  - if [ ${COVERAGE} = true ]; then coveralls --rcfile=.travis_coveragerc; fi
  - if [ ${COVERAGE} = true ]; then codecov; fi
